<?php
$this->load->view('Dashboard/Layout/opentag');
$this->load->view('Dashboard/Layout/header');
$this->load->view('Dashboard/Layout/opmain');
$this->load->view('Dashboard/Layout/menu');
$this->load->view('Dashboard/Layout/breadcrumb');
$this->load->view('Dashboard/Layout/konten');
$this->load->view('Dashboard/Layout/footer');
$this->load->view('Dashboard/Layout/closemain');
$this->load->view('Dashboard/Layout/closetag');